This script may be useful if you have a 3D model in FreeCAD
and want to lasercut it in segments to glue or stick together somehow.

To use, try something like this:

1. Copy and paste the script into the FreeCAD python console to define the function
2. Run bisectCrossSections(object, thickness), object is something like App.ActiveDocument.YourObjectName
3. Select all objects in the Solid_Slices group
4. Export to flattened SVG
5. Import to Inkscape
6. Select all with Ctrl-A
7. Choose Object->Ungroup (Shift-Ctrl-G)
8. Add a box the size of your plate to cut from, and lower box (Object->Lower to bottom)
9. Save as SVG from inkscape
10. Open SVGNest, load SVG
11. Select the box you added, and click "Start Nest"
12. Leave running until satisfied, save SVG and lasercut result

If you want to create Arch Panels instead of the simple outlines when
creating the slices, simply add the argument archPanels=True, something 
like the following example. The panels will have the thickness specified.

    bisectCrossSections(App.ActiveDocument.Cone002, 4.0, archPanels=True)

If you have a mesh and not a solid, you can try to convert it using this method:
https://www.youtube.com/watch?v=avVNfIswkMU

The script was originally based on the script available on:
http://freecadbuch.de/doku.php?id=blog:schnittmodell_eines_hauses_fuer_den_laser-schneider
